"""
Defines for outback-inverter
"""

DEVICEIP = '75.83.36.12'
DEVICEPORT = '502'

# Dynamic list of devices, contains a list of class objects 
DEVICES = []
DEPLOYMENTDEVICES = []
DEPLOYMENTCONFIG = None
DEPLOYMENTPHASE = None
DEPLOYMENTTYPE = None
FNDCCONFIG = None
FNDC = False

# Global Connection manager.
C = None

# Encryption - DO NOT TOUCH
ENCRYPTED = False
ENCRYPTIONKEY = None
BIAS = 0x0BCC
def LEFT7(value): return ((((value) & 0x01FF) << 7) | ((value) >> 9))
def RIGHT7(value): return ((((value) & 0X007F) << 9) | ((value) >> 7))
def DECRYPT(enc, value): return (LEFT7((value) ^ enc) ^ BIAS)
def ENCRYPT(enc, value): return (RIGHT7((value) ^ BIAS) ^ enc)


# SunSpec Definitions
SUNSPECID = '0x53756E53'
MAX_DEVICES= 28
SUNSPEC_MODBUS_REGISTER_OFFSET = 40001
ADDR_START = (SUNSPEC_MODBUS_REGISTER_OFFSET - 1)
SUNSPEC_COMMON_MODEL_BLOCK_DID = 1
SUNSPEC_AGGREGATOR_BLOCK_DID = 2
SUNSPEC_END_BLOCK_DID = 65535
SUNSPEC_INVERTER_SINGLE_DID = 101
SUNSPEC_INVERTER_SPLIT_DID = 102
SUNSPEC_INVERTER_3PHASE_DID = 103
SUNSPEC_BASIC_CC_DID = 64111
SUNSPEC_OUTBACK_DID = 64110
SUNSPEC_OUTBACK_FM_CC_DID = 64112
SUNSPEC_OUTBACK_FX_DID = 64113
SUNSPEC_OUTBACK_FX_CONFIG_DID = 64114
SUNSPEC_OUTBACK_GS_SPLIT_DID = 64115
SUNSPEC_OUTBACK_GS_CONFIG_DID = 64116
SUNSPEC_OUTBACK_GS_SINGLE_DID = 64117
SUNSPEC_OUTBACK_FNDC_DID = 64118
SUNSPEC_OUTBACK_FNDC_CONFIG_DID = 64119
SUNSPEC_OUTBACK_SYS_CONTROL_DID = 64120
SUNSPEC_OUTBACK_STATISTICS_DID = 64255

ENABLED_MAP = ['Disabled', 'Enabled']
STATUS_MAP = ['Not implemented','Off','Sleeping','Starting up','MPPT','Throttled','Shutting down','Fault','Standby']

COMMON_MDOFFSET = 0
COMMON_FIELDS= 9
COMMON_SIZE = 69
OUTBACK_MDOFFSET = (COMMON_MDOFFSET + COMMON_FIELDS)
OUTBACK_FIELDS = 166
OUTBACK_SIZE= 422
OB_SYS_CTRL_MDOFFSET = (OUTBACK_MDOFFSET + OUTBACK_FIELDS)
OB_SYS_CTRL_FIELDS = 27
OB_SYS_CTRL_SIZE= 29
CC_MDOFFSET = (OB_SYS_CTRL_MDOFFSET + OB_SYS_CTRL_FIELDS)
CC_FIELDS = 28
CC_SIZE = 28
CC_CONFIG_MDOFFSET = (CC_MDOFFSET + CC_FIELDS)
CC_CONFIG_FIELDS = 74
CC_CONFIG_SIZE = 90
I_MDOFFSET = (CC_CONFIG_MDOFFSET + CC_CONFIG_FIELDS)
I_FIELDS = 45
I_SIZE = 52
GS_CONFIG_MDOFFSET = (I_MDOFFSET + I_FIELDS)
GS_CONFIG_FIELDS = 74
GS_CONFIG_SIZE = 90
GS_SINGLE_MDOFFSET = (GS_CONFIG_MDOFFSET + GS_CONFIG_FIELDS)
GS_SINGLE_FIELDS = 48
GS_SINGLE_SIZE = 48
GS_SPLIT_MDOFFSET = (GS_SINGLE_MDOFFSET + GS_SINGLE_FIELDS)
GS_SPLIT_FIELDS = 60
GS_SPLIT_SIZE = 60
FX_CONFIG_MDOFFSET = (GS_SPLIT_MDOFFSET + GS_SPLIT_FIELDS)
FX_CONFIG_FIELDS = 58
FX_CONFIG_SIZE = 74
FX_MDOFFSET = (FX_CONFIG_MDOFFSET + FX_CONFIG_FIELDS)
FX_FIELDS = 38
FX_SIZE = 38
FNDC_CONFIG_MDOFFSET = (FX_MDOFFSET + FX_FIELDS)
FNDC_CONFIG_FIELDS = 38
FNDC_CONFIG_SIZE = 54
FNDC_MDOFFSET = (FNDC_CONFIG_MDOFFSET + FNDC_CONFIG_FIELDS)
FNDC_FIELDS = 76
FNDC_SIZE = 78
OB_STATS_MDOFFSET = (FNDC_MDOFFSET + FNDC_FIELDS)
OB_STATS_FIELDS = 58
OB_STATS_SIZE = 58
AGGREGATOR_MDOFFSET = (OB_STATS_MDOFFSET + OB_STATS_FIELDS)
AGGREGATOR_FIELDS = 12
AGGREGATOR_SIZE = 16
END_MDOFFSET = (AGGREGATOR_MDOFFSET + AGGREGATOR_FIELDS)
END_FIELDS = 2
END_SIZE = 2
NULL_MDOFFSET = 0
NULL_FIELDS = 0
NULL_SIZE = 0

C_STATUS_NORMAL = '0x00000000'    #Operating Normally
C_STATUS_ERROR = '0xFFFFFFFE'     #Generic Failure
C_STATUS_UNK = '0xFFFFFFFF'   #Status Unknown

STATUS_ABSORB_ENABLED = '0x0001'
STATUS_FLOAT_ENABLED = '0x0002'
STATUS_AC_USE  = '0x0004'
STATUS_INVERTER_OFF = '0x0008'
STATUS_INVERTER_SEARCH = '0x0010'
STATUS_INVERTER_ON = '0x0020'
STATUS_SELL_ENABLED = '0x0040'
STATUS_CHARGER_DISABLED = '0x0080'
STATUS_CHARGER_AUTO = '0x0100'
STATUS_CHARGER_BULK_AND_FLOAT = '0x0200'

OUTBACK_PASSWORD_SIZE = 8
SMTP_SERVER_NAME_SIZE = 20
SMTP_ACCOUNT_NAME_SIZE = 16
SMTP_EMAIL_PASSWORD_SIZE = 8
SMTP_EMAIL_USER_NAME_SIZE = 20
STATUS_EMAIL_SUBJECT_SIZE = 25
STATUS_EMAIL_TO_ADDR1_SIZE = 20
STATUS_EMAIL_TO_ADDR2_SIZE = 20
ALARM_EMAIL_SUBJECT_SIZE = 25
ALARM_EMAIL_TO_ADDR1_SIZE = 20
ALARM_EMAIL_TO_ADDR2_SIZE = 20
FTP_PASSWORD_SIZE  = 8
TELNET_PASSWORD_SIZE = 8
TIME_SERVER_NAME_SIZE = 20

ERR_LAST_WRITE_LIMIT_HIGH = 0
ERR_LAST_WRITE_LIMIT_LOW = 1
ERR_LAST_WRITE_INVALID  = 2
ERR_DHCP_FAILED    = 3
ERR_DNS_RESOLVE_FAILED  = 4
ERR_SMTP_AUTH_FAILED  = 5
ERR_SMTP_SEND_FAILED  = 6
ERR_FTP_ERROR    = 7
ERR_SD_CARD_ERROR   = 8
ERR_SNTP_FAILED    = 9
ERR_WRITE_WHILE_LOCKED  = 10
ERR_DEVICE_FW_UPDATE_INVALID = 11 
ERR_DEVICE_FW_UPDATE_FILE_NOT_FOUND = 12 
ERR_DEVICE_FW_UPDATE_FILE_INVALID = 13 
ERR_DEVICE_FW_UPDATE_FAILURE = 14 
ERR_OPERATION_NOT_SUPPORTED = 15

SUNSPEC_DEVICE_LOOKUP = {
                        1: 'SunSpec Common Model Block',
                        101: 'Single Phase Inverter',
                        102: 'Split Phase Inverter',
                        103: '3 Phase Inverter',
                        64110: 'OutBack Gateway',
                        64111: 'Basic Charge Controller',
                        64112: 'OutBack FM Charge Controller',
                        64113: 'OutBack FX Inverter',
                        64114: 'OutBack FX Inverter Configuration',
                        64115: 'OutBack Radian Split Phase Inverter',
                        64116: 'OutBack Radian Inverter Configuration',
                        64117: 'OutBack Radian Single Phase Inverter',
                        64118: 'OutBack FLEXnet-DC Battery Monitor',
                        64119: 'OutBack FLEXnet-DC Battery Monitor Configuration',
                        64120: 'OutBack System Control',
                        64255: 'OutBack OPTICS Packet Statistics',
                        65535: 'SunSpec End Block'
                        }

SUNSPEC_DEVICE_MAP = {
                            1: [
                                [1, 2, 'int32', 'NI_U', 'ni_sf', 0, 1, 'C_SunSpec_ID'],
                                [3, 1, 'int16', 'NI_U', 'ni_sf', 0, 1, 'C_SunSpec_DID'],
                                [4, 1, 'int16', 'REGISTERS_U', 'ni_sf', 0, 1, 'C_SunSpec_Length'],
                                [5, 16, 'string', 'NI_U', 'ni_sf', 0, 1, 'C_Manufacturer'],
                                [21, 16, 'string', 'NI_U', 'ni_sf', 0, 1, 'C_Model'],
                                [37, 8, 'string', 'NI_U', 'ni_sf', 0, 1, 'C_Options'],
                                [45, 6, 'string', 'NI_U', 'ni_sf', 0, 1, 'C_Version'],
                                [53, 16, 'string', 'NI_U', 'ni_sf', 0, 1, 'C_SerialNumber'],
                                [69, 1, 'int16', 'NI_U', 'ni_sf', 1, 1, 'C_DeviceAddress']
                            ],
                            2: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'A_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'A_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'A_Devices'],
                                [ 4, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'A_Count'],
                                [ 5, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'A_Update_Number'],
                                [ 6, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'A_Status'],
                                [ 7, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'A_Status_Vendor'],
                                [ 8, 2, 'int32', 'BITFIELD_U', 'NI_SF', 0, 1, 'A_Event'],
                                [ 10, 2, 'int32', 'BITFIELD_U', 'NI_SF', 0, 1, 'A_Event_Vendor'],
                                [ 12, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'A_Control'],
                                [ 13, 2, 'int32', 'ENUMERATED_U', 'NI_SF', 1, 1, 'A_Control_Vendor'],
                                [ 15, 2, 'int32', 'ENUMERATED_U', 'NI_SF', 1, 1, 'A_Control_Value']
                            ],
                            101: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'I_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'I_SunSpec_Length'],
                                [ 3, 1, 'int16', 'AMPS_U', 'I_AC_Current_SF', 0, 1, 'I_AC_Current'],
                                [ 4, 1, 'int16', 'AMPS_U', 'I_AC_Current_SF', 0, 1, 'I_AC_CurrentA'],
                                [ 5, 1, 'int16', 'AMPS_U', 'I_AC_Current_SF', 0, 1, 'I_AC_CurrentB'],
                                [ 6, 1, 'int16', 'AMPS_U', 'I_AC_Current_SF', 0, 1, 'I_AC_CurrentC'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_Current_SF'],
                                [ 8, 1, 'int16', 'VOLTS_U', 'I_AC_Voltage_SF', 0, 1, 'I_AC_VoltageAB'],
                                [ 9, 1, 'int16', 'VOLTS_U', 'I_AC_Voltage_SF', 0, 1, 'I_AC_VoltageBC'],
                                [ 10, 1, 'int16', 'VOLTS_U', 'I_AC_Voltage_SF', 0, 1, 'I_AC_VoltageCA'],
                                [ 11, 1, 'int16', 'VOLTS_U', 'I_AC_Voltage_SF', 0, 1, 'I_AC_VoltageAN'],
                                [ 12, 1, 'int16', 'VOLTS_U', 'I_AC_Voltage_SF', 0, 1, 'I_AC_VoltageBN'],
                                [ 13, 1, 'int16', 'VOLTS_U', 'I_AC_Voltage_SF', 0, 1, 'I_AC_VoltageCN'],
                                [ 14, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'I_AC_Voltage_SF'],
                                [ 15, 1, 'float2', 'KW_U', 'I_AC_Power_SF', 0, 1, 'I_AC_Power'],
                                [ 16, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_Power_SF'],
                                [ 17, 1, 'float', 'HERTZ_U', 'I_AC_Frequency_SF', 0, 1, 'I_AC_Frequency'],
                                [ 18, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_Frequency_SF'],
                                [ 19, 1, 'float2', 'VA_U', 'I_AC_VA_SF', 0, 1, 'I_AC_VA'],
                                [ 20, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_VA_SF'],
                                [ 21, 1, 'float2', 'VAR_U', 'I_AC_VAR_SF', 0, 1, 'I_AC_VAR'],
                                [ 22, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_VAR_SF'],
                                [ 23, 1, 'float2', 'PERCENTAGE_U', 'I_AC_PF_SF', 0, 1, 'I_AC_PF'],
                                [ 24, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_PF_SF'],
                                [ 25, 2, 'int32', 'WH_U', 'I_AC_Energy_WH_SF', 0, 1, 'I_AC_Energy_WH'],
                                [ 27, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_AC_Energy_WH_SF'],
                                [ 28, 1, 'int16', 'AMPS_U', 'I_DC_Current_SF', 0, 1, 'I_DC_Current'],
                                [ 29, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'I_DC_Current_SF'],
                                [ 30, 1, 'float', 'VOLTS_U', 'I_DC_Voltage_SF', 0, 1, 'I_DC_Voltage'],
                                [ 31, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_DC_Voltage_SF'],
                                [ 32, 1, 'int16', 'WATTS_U', 'I_DC_Power_SF', 0, 1, 'I_DC_Power'],
                                [ 33, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_DC_Power_SF'],
                                [ 34, 1, 'int16', 'DEGREES_C_U', 'I_Temp_SF', 0, 1, 'I_Temp_Cab'],
                                [ 35, 1, 'int16', 'DEGREES_C_U', 'I_Temp_SF', 0, 1, 'I_Temp_Sink'],
                                [ 36, 1, 'int16', 'DEGREES_C_U', 'I_Temp_SF', 0, 1, 'I_Temp_Trans'],
                                [ 37, 1, 'int16', 'DEGREES_C_U', 'I_Temp_SF', 0, 1, 'I_Temp_Other'],
                                [ 38, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'I_Temp_SF'],
                                [ 39, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'I_Status'],
                                [ 40, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Status_Vendor'],
                                [ 41, 2, 'hex8', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Event_1'],
                                [ 43, 2, 'hex8', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Event_2'],
                                [ 45, 2, 'hex8', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Event_1_Vendor'],
                                [ 48, 2, 'hex8', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Event_2_Vendor'],
                                [ 50, 2, 'hex8', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Event_3_Vendor'],
                                [ 52, 2, 'hex8', 'BITFIELD_U', 'NI_SF', 0, 1, 'I_Event_4_Vendor']
                            ],
                            64110: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'OutBack_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Major_Firmware_Number'],
                                [ 4, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Mid_Firmware_Number'],
                                [ 5, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Minor_Firmware_Number'],
                                [ 6, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Encryption_Key'],
                                [ 7, 7, 'string', 'NI_U', 'NI_SF', 0, 1 , 'OutBack_MAC_Address'],
                                [ 14, OUTBACK_PASSWORD_SIZE, 'string', 'NI_U', 'NI_SF', 1, 0, 'OutBack_Write_Password'],
                                [ 22, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Enable_DHCP'],
                                [ 23, 2, 'ipaddress', 'ADDR_U', 'NI_SF', 1, 1, 'OutBack_TCPIP_Address'],
                                [ 25, 2, 'ipaddress', 'ADDR_U', 'NI_SF', 1, 1, 'OutBack_TCPIP_Gateway'],
                                [ 27, 2, 'ipaddress', 'ADDR_U', 'NI_SF', 1, 1, 'OutBack_TCPIP_Netmask'],
                                [ 29, 2, 'ipaddress', 'ADDR_U', 'NI_SF', 1, 1, 'OutBack_TCPIP_DNS_1'],
                                [ 31, 2, 'ipaddress', 'ADDR_U', 'NI_SF', 1, 1, 'OutBack_TCPIP_DNS_2'],
                                [ 33, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Modbus_Port'],
                                [ 34, SMTP_SERVER_NAME_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_SMTP_Server_Name'],
                                [ 54, SMTP_ACCOUNT_NAME_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_SMTP_Account_Name'],
                                [ 70, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_SMTP_SSL_Enable'],
                                [ 71, SMTP_EMAIL_PASSWORD_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_SMTP_Email_Password'],
                                [ 79, SMTP_EMAIL_USER_NAME_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_SMTP_Email_User_Name'],
                                [ 99, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Status_Email_Interval'],
                                [ 100, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Status_Email_Status_Time'],
                                [ 101, STATUS_EMAIL_SUBJECT_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Status_Email_Subject_Line'],
                                [ 126, STATUS_EMAIL_TO_ADDR1_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Status_Email_To_Address_1'],
                                [ 146, STATUS_EMAIL_TO_ADDR2_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Status_Email_To_Address_2'],
                                [ 166, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Alarm_Email_Enable'],
                                [ 167, ALARM_EMAIL_SUBJECT_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Alarm_Email_Subject_Line'],
                                [ 192, ALARM_EMAIL_TO_ADDR1_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Alarm_Email_To_Address_1'],
                                [ 212, ALARM_EMAIL_TO_ADDR2_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Alarm_Email_To_Address_2'],
                                [ 232, FTP_PASSWORD_SIZE, 'string', 'NI_U', 'NI_SF', 1, 0, 'OutBack_FTP_Password'],
                                [ 240, TELNET_PASSWORD_SIZE, 'string', 'NI_U', 'NI_SF', 1, 0, 'OutBack_Telnet_Password'],
                                [ 248, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_SD_Card_Log_Write_Interval'],
                                [ 249, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_SD_Card_Log_Retain_Days'],
                                [ 250, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_SD_Card_Logging_Mode'],
                                [ 251, TIME_SERVER_NAME_SIZE, 'string', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Time_Server_Name'],
                                [ 271, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Enable_Time_Server'],
                                [ 272, 1, 'uhex4', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Set_Time_Zone'],
                                [ 273, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Enable_Float_Coordination'],
                                [ 274, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Enable_FNDC_Charge_Termination'],
                                [ 275, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Enable_FNDC_Grid_Tie_Control'],
                                [ 276, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Voltage_SF'],
                                [ 277, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Hour_SF'],
                                [ 278, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Mode'],
                                [ 279, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_AGS_Port'],
                                [ 280, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Port_Type'],
                                [ 281, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Generator_Type'],
                                [ 282, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_AGS_DC_Gen_Absorb_Voltage'],
                                [ 283, 1, 'float', 'HOURS_U', 'OutBack_Hour_SF', 1, 1, 'OutBack_AGS_DC_Gen_Absorb_Time'],
                                [ 284, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Fault_Time'],
                                [ 285, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Gen_Cool_Down_Time'],
                                [ 286, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Gen_Warm_Up_Time'],
                                [ 287, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Generator_Exercise_Mode'],
                                [ 288, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Exercise_Start_Hour'],
                                [ 289, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Exercise_Start_Minute'],
                                [ 290, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Exercise_Day'],
                                [ 291, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Exercise_Period'],
                                [ 292, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Exercise_Interval'],
                                [ 293, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Sell_Mode'],
                                [ 294, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_2_Min_Start_Mode'],
                                [ 295, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_AGS_2_Min_Start_Voltage'],
                                [ 296, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_2_Hour_Start_Mode'],
                                [ 297, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_AGS_2_Hour_Start_Voltage'],
                                [ 298, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_24_Hour_Start_Mode'],
                                [ 299, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_AGS_24_Hour_Start_Voltage'],
                                [ 300, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Load_Start_Mode'],
                                [ 301, 1, 'int16', 'KW_U', 'NI_SF', 1, 1, 'OutBack_AGS_Load_Start_kW'],
                                [ 302, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Load_Start_Delay'],
                                [ 303, 1, 'int16', 'KW_U', 'NI_SF', 1, 1, 'OutBack_AGS_Load_Stop_kW'],
                                [ 304, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Load_Stop_Delay'],
                                [ 305, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_SOC_Start_Mode'],
                                [ 306, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'OutBack_AGS_SOC_Start_Percentage'],
                                [ 307, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'OutBack_AGS_SOC_Stop_Percentage'],
                                [ 308, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Enable_Full_Charge_Mode'],
                                [ 309, 1, 'int16', 'DAYS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Full_Charge_Interval'],
                                [ 310, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Mode'],
                                [ 311, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekday_Start_Hour'],
                                [ 312, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekday_Start_Minute'],
                                [ 313, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekday_Stop_Hour'],
                                [ 314, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekday_Stop_Minute'],
                                [ 315, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekend_Start_Hour'],
                                [ 316, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekend_Start_Minute'],
                                [ 317, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekend_Stop_Hour'],
                                [ 318, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Must_Run_Weekend_Stop_Minute'],
                                [ 319, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Mode'],
                                [ 320, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekday_Start_Hour'],
                                [ 321, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekday_Start_Minute'],
                                [ 322, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekday_Stop_Hour'],
                                [ 323, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekday_Stop_Minute'],
                                [ 324, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekend_Start_Hour'],
                                [ 325, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekend_Start_Minute'],
                                [ 326, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekend_Stop_Hour'],
                                [ 327, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Quiet_Time_Weekend_Stop_Minute'],
                                [ 328, 2, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_Total_Generator_Run_Time'],
                                [ 330, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_HBX_Mode'],
                                [ 331, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_HBX_Grid_Connect_Voltage'],
                                [ 332, 1, 'int16', 'HOURS_U', 'OutBack_Hour_SF', 1, 1, 'OutBack_HBX_Grid_Connect_Delay'],
                                [ 333, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_HBX_Grid_Disconnect_Voltage'],
                                [ 334, 1, 'int16', 'HOURS_U', 'OutBack_Hour_SF', 1, 1, 'OutBack_HBX_Grid_Disconnect_Delay'],
                                [ 335, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'OutBack_HBX_Grid_Connect_SOC'],
                                [ 336, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'OutBack_HBX_Grid_Disconnect_SOC'],
                                [ 337, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Mode'],
                                [ 338, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekday_Start_Hour'],
                                [ 339, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekday_Start_Minute'],
                                [ 340, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekday_Stop_Hour'],
                                [ 341, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekday_Stop_Minute'],
                                [ 342, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekend_Start_Hour'],
                                [ 343, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekend_Start_Minute'],
                                [ 344, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekend_Stop_Hour'],
                                [ 345, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_1_Weekend_Stop_Minute'],
                                [ 346, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_2_Mode'],
                                [ 347, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_2_Weekday_Start_Hour'],
                                [ 348, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_2_Weekday_Start_Minute'],
                                [ 349, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_2_Weekday_Stop_Hour'],
                                [ 350, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_2_Weekday_Stop_Minute'],
                                [ 351, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_3_Mode'],
                                [ 352, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_3_Weekday_Start_Hour'],
                                [ 353, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_3_Weekday_Start_Minute'],
                                [ 354, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_3_Weekday_Stop_Hour'],
                                [ 355, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Grid_Use_Interval_3_Weekday_Stop_Minute'],
                                [ 356, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Load_Grid_Transfer_Mode'],
                                [ 357, 1, 'float', 'KW_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_Load_Grid_Transfer_Threshold'],
                                [ 358, 1, 'int16', 'SECS_U', 'NI_SF', 1, 1, 'OutBack_Load_Grid_Transfer_Connect_Delay'],
                                [ 359, 1, 'int16', 'SECS_U', 'NI_SF', 1, 1, 'OutBack_Load_Grid_Transfer_Disconnect_Delay'],
                                [ 360, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_Load_Grid_Transfer_Connect_Battery_Voltage'],
                                [ 361, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 1, 1, 'OutBack_Load_Grid_Transfer_Re_Connect_Battery_Voltage'],
                                [ 362, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Global_Charger_Control_Mode'],
                                [ 363, 1, 'int16', 'AMPS_U', 'NI_SF', 1, 1, 'OutBack_Global_Charger_Output_Limit'],
                                [ 364, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Radian_AC_Coupled_Mode'],
                                [ 365, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Radian_AC_Coupled_AUX_Port'],
                                [ 366, 2, 'int32', 'NI_U', 'NI_SF', 1, 0, 'OutBack_URL_Lock'],
                                [ 368, 20, 'string', 'NI_U', 'NI_SF', 1, 0, 'OutBack_Web_Reporting_Base_URL'],
                                [ 388, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Web_User_Logged_In_Status'],
                                [ 389, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'OutBack_HUB_Type'],
                                [ 390, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_HUB_Major_Firmware_Number'],
                                [ 391, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_HUB_Mid_Firmware_Number'],
                                [ 392, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_HUB_Minor_Firmware_Number'],
                                [ 393, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Year'],
                                [ 394, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Month'],
                                [ 395, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Day'],
                                [ 396, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Hour'],
                                [ 397, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Minute'],
                                [ 398, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Second'],
                                [ 399, 1, 'int16', 'DEGREES_C_U', 'OutBack_Temp_SF', 0, 1, 'OutBack_Temp_Batt'],
                                [ 400, 1, 'int16', 'DEGREES_C_U', 'OutBack_Temp_SF', 0, 1, 'OutBack_Temp_Ambient'],
                                [ 401, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OutBack_Temp_SF'],
                                [ 402, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'OutBack_Error'],
                                [ 403, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'OutBack_Status'],
                                [ 404, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Update_Device_Firmware_Port'],
                                [ 405, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'OutBack_Gateway_Type'],
                                [ 406, 1, 'int16', 'VOLTS_U', 'NI_SF', 0, 1, 'OutBack_System_Voltage'],
                                [ 407, 1, 'float', 'VOLTS_U', 'OutBack_Voltage_SF', 0, 1, 'OutBack_Measured_System_Voltage'],
                                [ 408, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_AGS_AC_Reconnect_Delay'],
                                [ 409, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Multi_Phase_Coordination'],
                                [ 410, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Sched_1_AC_Mode'],
                                [ 411, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Sched_1_AC_Mode_Hour'],
                                [ 412, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Sched_1_AC_Mode_Min'],
                                [ 413, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Sched_2_AC_Mode'],
                                [ 414, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Sched_2_AC_Mode_Hour'],
                                [ 415, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Sched_2_AC_Mode_Min'],
                                [ 416, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OutBack_Sched_3_AC_Mode'],
                                [ 417, 1, 'int16', 'HOURS_U', 'NI_SF', 1, 1, 'OutBack_Sched_3_AC_Mode_Hour'],
                                [ 418, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'OutBack_Sched_3_AC_Mode_Min'],
                                [ 419, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Auto_reboot'],
                                [ 420, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Spare_Reg_2'],
                                [ 421, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Spare_Reg_3'],
                                [ 422, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OutBack_Spare_Reg_4']
                            ],
                            64111: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CC_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'CC_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CC_port_number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CC_Power_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CC_AH_SF'],
                                [ 8, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CC_KWH_SF'],
                                [ 9, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_Batt_Voltage'],
                                [ 10, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_Array_Voltage'],
                                [ 11, 1, 'int16', 'AMPS_U', 'CC_Current_SF', 0, 1, 'CC_Batt_Current'],
                                [ 12, 1, 'int16', 'AMPS_U', 'CC_Power_SF', 0, 1, 'CC_Array_Current'],
                                [ 13, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'CC_Charger_State'],
                                [ 14, 1, 'int16', 'WATTS_U', 'CC_Power_SF', 0, 1, 'CC_Watts'],
                                [ 15, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_Todays_Min_Battery_Volts'],
                                [ 16, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_Todays_Max_Battery_Volts'],
                                [ 17, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_VOC'],
                                [ 18, 1, 'float', 'VOLTS_U', 'NI_SF', 0, 1, 'CC_Todays_Peak_VOC'],
                                [ 19, 1, 'float', 'KWH_U', 'CC_KWH_SF', 0, 1, 'CC_Todays_kWH'],
                                [ 20, 1, 'int16', 'AH_U', 'CC_AH_SF', 0, 1, 'CC_Todays_AH'],
                                [ 21, 1, 'int16', 'KWH_U', 'NI_SF', 0, 1, 'CC_Lifetime_kWH_Hours'],
                                [ 22, 1, 'int16', 'KAH_U', 'CC_KWH_SF', 0, 1, 'CC_Lifetime_kAmp_Hours'],
                                [ 23, 1, 'int16', 'WATTS_U', 'CC_Power_SF', 0, 1, 'CC_Lifetime_Max_Watts'],
                                [ 24, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_Lifetime_Max_Battery_Volts'],
                                [ 25, 1, 'float', 'VOLTS_U', 'CC_Voltage_SF', 0, 1, 'CC_Lifetime_Max_VOC'],
                                [ 26, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CC_Temp_SF'],
                                [ 27, 1, 'int16', 'DEGREES_C_U', 'CC_Temp_SF', 0, 1, 'CC_Temp_Output_FETs'],
                                [ 28, 1, 'int16', 'DEGREES_C_U', 'CC_Temp_SF', 0, 1, 'CC_Temp_Enclosure']
                            ],
                            64112: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'CCconfig_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_port_number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Hours_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Power_SF'],
                                [ 8, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_AH_SF'],
                                [ 9, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_KWH_SF'],
                                [ 10, 1, 'int16', 'BITFIELD_U', 'NI_SF', 0, 1, 'CCconfig_Faults'],
                                [ 11, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Absorb_Volts'],
                                [ 12, 1, 'int16', 'HOURS_U', 'CCconfig_Hours_SF', 1, 1, 'CCconfig_Absorb_Time_Hours'],
                                [ 13, 1, 'int16', 'AMPS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Absorb_End_Amps'],
                                [ 14, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Rebulk_Volts'],
                                [ 15, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Float_Volts'],
                                [ 16, 1, 'int16', 'AMPS_U', 'CCconfig_Current_SF', 1, 1, 'CCconfig_Bulk_Current'],
                                [ 17, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_EQ_Volts'],
                                [ 18, 1, 'float', 'HOURS_U', 'NI_SF', 1, 1, 'CCconfig_EQ_Time_Hours'],
                                [ 19, 1, 'float', 'DAYS_U', 'NI_SF', 1, 1, 'CCconfig_Auto_EQ_Days'],
                                [ 20, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_MPPT_Mode'],
                                [ 21, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_Sweep_Width'],
                                [ 22, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_Sweep_Max_Percentage'],
                                [ 23, 1, 'int16', 'PERCENTAGE_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_U_Pick_PWM_Duty_Cycle'],
                                [ 24, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_Grid_Tie_Mode'],
                                [ 25, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_Temp_Comp_Mode'],
                                [ 26, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Temp_Comp_Lower_Limit_Volts'],
                                [ 27, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Temp_Comp_Upper_Limit_Volts'],
                                [ 28, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'CCconfig_Temp_Comp_Slope'], 
                                [ 29, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_Auto_Restart_Mode'],
                                [ 30, 1, 'int16', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Wakeup_VOC'],
                                [ 31, 1, 'int16', 'AMPS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Snooze_Mode_Amps'],
                                [ 32, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'CCconfig_Wakeup_Interval'],
                                [ 33, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_AUX_Mode'],
                                [ 34, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_AUX_Control'],
                                [ 35, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'CCconfig_AUX_State'],
                                [ 36, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'CCconfig_AUX_Polarity'],
                                [ 37, 1, 'int16', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Low_Batt_Disconnect'],
                                [ 38, 1, 'int16', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Low_Batt_Reconnect'],
                                [ 39, 1, 'int16', 'SECS_U', 'NI_SF', 1, 1, 'CCconfig_AUX_Low_Batt_Disconnect_Delay'],
                                [ 40, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Vent_Fan_Volts'],
                                [ 41, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_PV_Limit_Volts'],
                                [ 42, 1, 'int16', 'SECS_U', 'CCconfig_Hours_SF', 1, 1, 'CCconfig_AUX_PV_Limit_Hold_Time'],
                                [ 43, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Night_Light_Thres_Volts'],
                                [ 44, 1, 'int16', 'HOURS_U', 'CCconfig_Hours_SF', 1, 1, 'CCconfig_Night_Light_ON_Hours'],
                                [ 45, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'CCconfig_Night_Light_ON_Hyst_Time'],
                                [ 46, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'CCconfig_Night_Light_OFF_Hyst_Time'],
                                [ 47, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Error_Battery_Volts'],
                                [ 48, 1, 'int16', 'SECS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Divert_Hold_Time'],
                                [ 49, 1, 'int16', 'SECS_U', 'NI_SF', 1, 1, 'CCconfig_AUX_Divert_Delay_Time'],
                                [ 50, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Divert_Relative_Volts'],
                                [ 51, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_AUX_Divert_Hyst_Volts'],
                                [ 52, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Major_Firmware_Number'],
                                [ 53, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Mid_Firmware_Number'],
                                [ 54, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Minor_Firmware_Number'],
                                [ 55, 1, 'uhex4', 'DAYS_U', 'NI_SF', 1, 1, 'CCconfig_Set_Log_Day_Offset'],
                                [ 56, 1, 'uhex4', 'DAYS_U', 'NI_SF', 0, 1, 'CCconfig_Get_Current_Log_Day_Offset'],
                                [ 57, 1, 'int16', 'AH_U', 'CCconfig_AH_SF', 0, 1, 'CCconfig_Log_Daily_AH'],
                                [ 58, 1, 'float', 'KWH_U', 'CCconfig_KWH_SF', 0, 1, 'CCconfig_Log_Daily_kWH'],
                                [ 59, 1, 'int16', 'AMPS_U', 'CCconfig_Voltage_SF', 0, 1, 'CCconfig_Log_Daily_Max_Output_Amps'],
                                [ 60, 1, 'int16', 'WATTS_U', 'CCconfig_Power_SF', 0, 1, 'CCconfig_Log_Daily_Max_Output_Watts'],
                                [ 61, 1, 'int16', 'MINS_U', 'NI_SF', 0, 1, 'CCconfig_Log_Daily_Absorb_Time'],
                                [ 62, 1, 'int16', 'MINS_U', 'NI_SF', 0, 1, 'CCconfig_Log_Daily_Float_Time'],
                                [ 63, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 0, 1, 'CCconfig_Log_Daily_Min_Batt_Volts'],
                                [ 64, 1, 'float', 'VOLTS_U', 'CCconfig_Voltage_SF', 0, 1, 'CCconfig_Log_Daily_Max_Batt_Volts'],
                                [ 65, 1, 'float', 'VOLTS_U', 'NI_SF', 0, 1, 'CCconfig_Log_Daily_Max_Input_Volts'],
                                [ 66, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Clear_Log_Read'],
                                [ 67, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'CCconfig_Clear_Log_Write_Complement'],
                                [ 68, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Stats_Maximum_Reset_Read'],
                                [ 69, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'CCconfig_Stats_Maximum_Write_Complement'],
                                [ 70, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Stats_Totals_Reset_Read'],
                                [ 71, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'CCconfig_Stats_Totals_Write_Complement'],
                                [ 72, 1, 'uhex4', 'VOLTS_U', 'CCconfig_Voltage_SF', 1, 1, 'CCconfig_Battery_Voltage_Calibrate_Offset'],
                                [ 73, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Serial_Number'],
                                [ 82, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'CCconfig_Model_Number']
                            ],
                            64113: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FX_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'FX_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FX_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FX_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FX_AC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FX_AC_Voltage_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FX_AC_Frequency_SF'],
                                [ 8, 1, 'int16', 'NI_U', 'FX_AC_Current_SF', 0, 1, 'FX_Inverter_Output_Current'],
                                [ 9, 1, 'int16', 'NI_U', 'FX_AC_Current_SF', 0, 1, 'FX_Inverter_Charge_Current'],
                                [ 10, 1, 'int16', 'NI_U', 'FX_AC_Current_SF', 0, 1, 'FX_Inverter_Buy_Current'],
                                [ 11, 1, 'int16', 'NI_U', 'FX_AC_Current_SF', 0, 1, 'FX_Inverter_Sell_Current'],
                                [ 12, 1, 'int16', 'VOLTS_U', 'FX_AC_Voltage_SF', 0, 1, 'FX_AC_Output_Voltage'],
                                [ 13, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'FX_Inverter_Operating_Mode'],
                                [ 14, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'FX_Error_Flags'],
                                [ 15, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'FX_Warning_Flags'],
                                [ 16, 1, 'float', 'VOLTS_U', 'FX_DC_Voltage_SF', 0, 1, 'FX_Battery_Voltage'],
                                [ 17, 1, 'float', 'VOLTS_U', 'FX_DC_Voltage_SF', 0, 1, 'FX_Temp_Comp_Target_Voltage'],
                                [ 18, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'FX_AUX_Output_State'],
                                [ 19, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'FX_Transformer_Temp'],
                                [ 20, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'FX_Capacitor_Temp'],
                                [ 21, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'FX_FET_Temp'],
                                [ 22, 1, 'float', 'CYCLES_U', 'FX_AC_Frequency_SF', 0, 1, 'FX_AC_Input_Frequency'],
                                [ 23, 1, 'int16', 'VOLTS_U', 'FX_AC_Voltage_SF', 0, 1, 'FX_AC_Input_Voltage'],
                                [ 24, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'FX_AC_Input_State'],
                                [ 25, 1, 'int16', 'VOLTS_U', 'FX_AC_Voltage_SF', 1, 1, 'FX_Minimum_AC_Input_Voltage'],
                                [ 26, 1, 'int16', 'VOLTS_U', 'FX_AC_Voltage_SF', 1, 1, 'FX_Maximum_AC_Input_Voltage'],
                                [ 27, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'FX_Sell_Status'],
                                [ 28, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FX_kWh_SF'],
                                [ 29, 1, 'float', 'KWH_U', 'FX_kWh_SF', 0, 1, 'FX_Buy_kWh'],
                                [ 30, 1, 'float', 'KWH_U', 'FX_kWh_SF', 0, 1, 'FX_Sell_kWh'],
                                [ 31, 1, 'float', 'KWH_U', 'FX_kWh_SF', 0, 1, 'FX_Output_kWh'],
                                [ 32, 1, 'float', 'KWH_U', 'FX_kWh_SF', 0, 1, 'FX_Charger_kWh'],
                                [ 33, 1, 'float', 'KW_U', 'FX_kWh_SF', 0, 1, 'FX_Output_kW'],
                                [ 34, 1, 'float', 'KW_U', 'FX_kWh_SF', 0, 1, 'FX_Buy_kW'],
                                [ 35, 1, 'float', 'KW_U', 'FX_kWh_SF', 0, 1, 'FX_Sell_kW'],
                                [ 36, 1, 'float', 'KW_U', 'FX_kWh_SF', 0, 1, 'FX_Charge_kW'],
                                [ 37, 1, 'float', 'KW_U', 'FX_kWh_SF', 0, 1, 'FX_Load_kW'],
                                [ 38, 1, 'float', 'KW_U', 'FX_kWh_SF', 0, 1, 'FX_AC_Couple_kW']
                            ],
                            64114 : [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'FXconfig_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_AC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_AC_Voltage_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Time_SF'],
                                [ 8, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Major_Firmware_Number'],
                                [ 9, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Mid_Firmware_Number'],
                                [ 10, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Minor_Firmware_Number'],
                                [ 11, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_Absorb_Volts'],
                                [ 12, 1, 'float', 'HOURS_U', 'FXconfig_Time_SF', 1, 1, 'FXconfig_Absorb_Time_Hours'],
                                [ 13, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_Float_Volts'],
                                [ 14, 1, 'float', 'HOURS_U', 'FXconfig_Time_SF', 1, 1, 'FXconfig_Float_Time_Hours'],
                                [ 15, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_ReFloat_Volts'],
                                [ 16, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_EQ_Volts'],
                                [ 17, 1, 'float', 'HOURS_U', 'FXconfig_Time_SF', 1, 1, 'FXconfig_EQ_Time_Hours'],
                                [ 18, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FXconfig_Search_Sensitivity'],
                                [ 19, 1, 'int16', 'CYCLES_U', 'NI_SF', 1, 1, 'FXconfig_Search_Pulse_Length'],
                                [ 20, 1, 'int16', 'CYCLES_U', 'NI_SF', 1, 1, 'FXconfig_Search_Pulse_Spacing'],
                                [ 21, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_AC_Input_Type'],
                                [ 22, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_Input_Support'],
                                [ 23, 1, 'float', 'NI_U', 'FXconfig_AC_Current_SF', 1, 1, 'FXconfig_Grid_AC_Input_Current_Limit'],
                                [ 24, 1, 'float', 'NI_U', 'FXconfig_AC_Current_SF', 1, 1, 'FXconfig_Gen_AC_Input_Current_Limit'],
                                [ 25, 1, 'float', 'NI_U', 'FXconfig_AC_Current_SF', 1, 1, 'FXconfig_Charger_AC_Input_Current_Limit'],
                                [ 26, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_Charger_Operating_Mode'],
                                [ 27, 1, 'int16', 'VOLTS_U', 'FXconfig_AC_Voltage_SF', 1, 1, 'FXconfig_Grid_Lower_Input_Voltage_Limit'],
                                [ 28, 1, 'int16', 'VOLTS_U', 'FXconfig_AC_Voltage_SF', 1, 1, 'FXconfig_Grid_Upper_Input_Voltage_Limit'],
                                [ 29, 1, 'int16', 'CYCLES_U', 'NI_SF', 1, 1, 'FXconfig_Grid_Transfer_Delay'],
                                [ 30, 1, 'int16', 'VOLTS_U', 'FXconfig_AC_Voltage_SF', 1, 1, 'FXconfig_Gen_lower_Input_Voltage_Limit'],
                                [ 31, 1, 'int16', 'VOLTS_U', 'FXconfig_AC_Voltage_SF', 1, 1, 'FXconfig_Gen_Upper_Input_Voltage_Limit'],
                                [ 32, 1, 'int16', 'CYCLES_U', 'NI_SF', 1, 1, 'FXconfig_Gen_Transfer_Delay'],
                                [ 33, 1, 'float', 'MINS_U', 'FXconfig_Time_SF', 1, 1, 'FXconfig_Gen_Connect_Delay'],
                                [ 34, 1, 'int16', 'VOLTS_U', 'FXconfig_AC_Voltage_SF', 1, 1, 'FXconfig_AC_Output_Voltage'],
                                [ 35, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_Low_Battery_Cut_Out_Voltage'],
                                [ 36, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_Low_Battery_Cut_In_Voltage'],
                                [ 37, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_AUX_Mode'],
                                [ 38, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_AUX_Control'],
                                [ 39, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_AUX_Load_Shed_Enable_Voltage'],
                                [ 40, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_AUX_Gen_Alert_On_Voltage'],
                                [ 41, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FXconfig_AUX_Gen_Alert_On_Delay'],
                                [ 42, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_AUX_Gen_Alert_OFF_Voltage'],
                                [ 43, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FXconfig_AUX_Gen_Alert_OFF_Delay'],
                                [ 44, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_AUX_Vent_Fan_Enable_Voltage'],
                                [ 45, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FXconfig_AUX_Vent_Fan_Off_Period'],
                                [ 46, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_AUX_Divert_Enable_Voltage'],
                                [ 47, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FXconfig_AUX_Divert_Off_Delay'],
                                [ 48, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_Stacking_Mode'],
                                [ 49, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FXconfig_Master_Power_Save_Level'],
                                [ 50, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FXconfig_Slave_Power_Save_Level'],
                                [ 51, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_Sell_Volts'],
                                [ 52, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_Grid_Tie_Window'],
                                [ 53, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FXconfig_Grid_Tie_Enable'],
                                [ 54, 1, 'uhex4', 'VOLTS_U', 'NI_SF', 1, 1, 'FXconfig_AC_Input_Voltage_Cal_Factor'],
                                [ 55, 1, 'uhex4', 'VOLTS_U', 'NI_SF', 1, 1, 'FXconfig_AC_Output_Voltage_Cal_Factor'],
                                [ 56, 1, 'float', 'VOLTS_U', 'FXconfig_DC_Voltage_SF', 1, 1, 'FXconfig_Battery_Voltage_Cal_Factor'],
                                [ 57, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Serial_Number'],
                                [ 66, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'FXconfig_Model_Number']
                            ],
                            64115: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'GS_Split_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_AC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_AC_Voltage_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_Frequency_SF'],
                                [ 8, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L1_Inverter_Output_Current'],
                                [ 9, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L1_Inverter_Charge_Current'],
                                [ 10, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L1_Inverter_Buy_Current'],
                                [ 11, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L1_Inverter_Sell_Current'],
                                [ 12, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_L1_Grid_Input_AC_Voltage'],
                                [ 13, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_L1_Gen_Input_AC_Voltage'],
                                [ 14, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_L1_AC_Output_Voltage'],
                                [ 15, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L2_Inverter_Output_Current'],
                                [ 16, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L2_Inverter_Charge_Current'],
                                [ 17, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L2_Inverter_Buy_Current'],
                                [ 18, 1, 'int16', 'NI_U', 'GS_Split_AC_Current_SF', 0, 1, 'GS_Split_L2_Inverter_Sell_Current'],
                                [ 19, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_L2_Grid_Input_AC_Voltage'],
                                [ 20, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_L2_Gen_Input_AC_Voltage'],
                                [ 21, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_L2_AC_Output_Voltage'],
                                [ 22, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Split_Inverter_Operating_Mode'],
                                [ 23, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'GS_Split_Error_Flags'],
                                [ 24, 1, 'hex4', 'BITFIELD_U', 'NI_SF', 0, 1, 'GS_Split_Warning_Flags'],
                                [ 25, 1, 'float', 'VOLTS_U', 'GS_Split_DC_Voltage_SF', 0, 1, 'GS_Split_Battery_Voltage'],
                                [ 26, 1, 'float', 'VOLTS_U', 'GS_Split_DC_Voltage_SF', 0, 1, 'GS_Split_Temp_Comp_Target_Voltage'],
                                [ 27, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Split_AUX_Output_State'],
                                [ 28, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Split_AUX_Relay_Output_State'],
                                [ 29, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_L_Module_Transformer_Temp'],
                                [ 30, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_L_Module_Capacitor_Temp'],
                                [ 31, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_L_Module_FET_Temp'],
                                [ 32, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_R_Module_Transformer_Temp'],
                                [ 33, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_R_Module_Capacitor_Temp'],
                                [ 34, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_R_Module_FET_Temp'],
                                [ 35, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Split_Battery_Temperature'],
                                [ 36, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Split_AC_Input_Selection'],
                                [ 37, 1, 'int16', 'CYCLES_U', 'GS_Split_Frequency_SF', 0, 1, 'GS_Split_AC_Input_Frequency'],
                                [ 38, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 0, 1, 'GS_Split_AC_Input_Voltage'],
                                [ 39, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Split_AC_Input_State'],
                                [ 40, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 1, 1, 'GS_Split_Minimum_AC_Input_Voltage'],
                                [ 41, 1, 'float', 'VOLTS_U', 'GS_Split_AC_Voltage_SF', 1, 1, 'GS_Split_Maximum_AC_Input_Voltage'],
                                [ 42, 1, 'int16', 'BITFIELD_U', 'NI_SF', 0, 1, 'GS_Split_Sell_Status'],
                                [ 43, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Split_kWh_SF'],
                                [ 44, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC1_L1_Buy_kWh'],
                                [ 45, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC2_L1_Buy_kWh'],
                                [ 46, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC1_L1_Sell_kWh'],
                                [ 47, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC2_L1_Sell_kWh'],
                                [ 48, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_L1_Output_kWh'],
                                [ 49, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC1_L2_Buy_kWh'],
                                [ 50, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC2_L2_Buy_kWh'],
                                [ 51, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC1_L2_Sell_kWh'],
                                [ 52, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC2_L2_Sell_kWh'],
                                [ 53, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_L2_Output_kWh'],
                                [ 54, 1, 'float', 'KWH_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_Charger_kWh'],
                                [ 55, 1, 'float', 'KW_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_Output_kW'],
                                [ 56, 1, 'float', 'KW_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_Buy_kW'],
                                [ 57, 1, 'float', 'KW_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_Sell_kW'],
                                [ 58, 1, 'float', 'KW_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_Charge_kW'],
                                [ 59, 1, 'float', 'KW_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_Load_kW'],
                                [ 60, 1, 'float', 'KW_U', 'GS_Split_kWh_SF', 0, 1, 'GS_Split_AC_Couple_kW']
                            ],
                            64116: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'GSconfig_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_AC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_AC_Voltage_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_Time_SF'],
                                [ 8, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_Major_firmware_number'],
                                [ 9, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_Mid_firmware_number'],
                                [ 10, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_Minor_firmware_number'],
                                [ 11, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Absorb_Volts'],
                                [ 12, 1, 'float', 'HOURS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_Absorb_Time_Hours'],
                                [ 13, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Float_Volts'],
                                [ 14, 1, 'float', 'HOURS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_Float_Time_Hours'],
                                [ 15, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_ReFloat_Volts'],
                                [ 16, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_EQ_Volts'],
                                [ 17, 1, 'float', 'HOURS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_EQ_Time_Hours'],
                                [ 18, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'GSconfig_Search_Sensitivity'],
                                [ 19, 1, 'int16', 'CYCLES_U', 'NI_SF', 1, 1, 'GSconfig_Search_Pulse_Length'],
                                [ 20, 1, 'int16', 'CYCLES_U', 'NI_SF', 1, 1, 'GSconfig_Search_Pulse_Spacing'],
                                [ 21, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_AC_Input_Select_Priority'],
                                [ 22, 1, 'int16', 'NI_U', 'GSconfig_AC_Current_SF', 1, 1, 'GSconfig_Grid_AC_Input_Current_Limit'],
                                [ 23, 1, 'int16', 'NI_U', 'GSconfig_AC_Current_SF', 1, 1, 'GSconfig_Gen_AC_Input_Current_Limit'],
                                [ 24, 1, 'int16', 'NI_U', 'GSconfig_AC_Current_SF', 1, 1, 'GSconfig_Charger_AC_Input_Current_Limit'],
                                [ 25, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Charger_Operating_Mode'],
                                [ 26, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_AC_Coupled'],
                                [ 27, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Grid_Input_Mode'],
                                [ 28, 1, 'float', 'VOLTS_U', 'GSconfig_AC_Voltage_SF', 1, 1, 'GSconfig_Grid_Lower_Input_Voltage_Limit'],
                                [ 29, 1, 'float', 'VOLTS_U', 'GSconfig_AC_Voltage_SF', 1, 1, 'GSconfig_Grid_Upper_Input_Voltage_Limit'],
                                [ 30, 1, 'float', 'NI_U', 'NI_SF', 1, 1, 'GSconfig_Grid_Transfer_Delay'],
                                [ 31, 1, 'float', 'MINS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_Grid_Connect_Delay'],
                                [ 32, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Gen_Input_Mode'],
                                [ 33, 1, 'int16', 'VOLTS_U', 'GSconfig_AC_Voltage_SF', 1, 1, 'GSconfig_Gen_Lower_Input_Voltage_Limit'],
                                [ 34, 1, 'int16', 'VOLTS_U', 'GSconfig_AC_Voltage_SF', 1, 1, 'GSconfig_Gen_Upper_Input_Voltage_Limit'],
                                [ 35, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'GSconfig_Gen_Transfer_Delay'],
                                [ 36, 1, 'int16', 'MINS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_Gen_Connect_Delay'],
                                [ 37, 1, 'float', 'VOLTS_U', 'GSconfig_AC_Voltage_SF', 1, 1, 'GSconfig_AC_Output_Voltage'],
                                [ 38, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Low_Battery_Cut_Out_Voltage'],
                                [ 39, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Low_Battery_Cut_In_Voltage'],
                                [ 40, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_AUX_Mode'],
                                [ 41, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_AUX_Control'],
                                [ 42, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_AUX_ON_Battery_Voltage'],
                                [ 43, 1, 'int16', 'MINS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_AUX_ON_Delay_Time'],
                                [ 44, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_AUX_OFF_Battery_Voltage'],
                                [ 45, 1, 'int16', 'MINS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_AUX_OFF_Delay_Time'],
                                [ 46, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_AUX_Relay_Mode'],
                                [ 47, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_AUX_Relay_Control'], 
                                [ 48, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_AUX_Relay_ON_Battery_Voltage'],
                                [ 49, 1, 'int16', 'MINS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_AUX_Relay_ON_Delay_Time'],
                                [ 50, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_AUX_Relay_OFF_Battery_Voltage'],
                                [ 51, 1, 'int16', 'MINS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_AUX_Relay_OFF_Delay_Time'],
                                [ 52, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Stacking_Mode'],
                                [ 53, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'GSconfig_Master_Power_Save_Level'],
                                [ 54, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'GSconfig_Slave_Power_Save_Level'],
                                [ 55, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Sell_Volts'],
                                [ 56, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Grid_Tie_Window'],
                                [ 57, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Grid_Tie_Enable'],
                                [ 58, 1, 'float', 'VOLTS_U', 'NI_SF', 1, 1, 'GSconfig_Grid_AC_Input_Voltage_Cal_Factor'],
                                [ 59, 1, 'float', 'VOLTS_U', 'NI_SF', 1, 1, 'GSconfig_Gen_AC_Input_Voltage_Cal_Factor'],
                                [ 60, 1, 'float', 'VOLTS_U', 'NI_SF', 1, 1, 'GSconfig_AC_Output_Voltage_Cal_Factor'],
                                [ 61, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Battery_Voltage_Cal_Factor'],
                                [ 62, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_ReBulk_Volts'],
                                [ 63, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Mini_Grid_LBX_Volts'],
                                [ 64, 1, 'float', 'HOURS_U', 'GSconfig_Time_SF', 1, 1, 'GSconfig_Mini_Grid_LBX_Delay'],
                                [ 65, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Grid_Zero_DoD_Volts'],
                                [ 66, 1, 'int16', 'NI_U', 'GSconfig_AC_Current_SF', 1, 1, 'GSconfig_Grid_Zero_DoD_Max_Offset_AC_Amps'],
                                [ 67, 9, 'string', 'NI_U', 'NI_SF', 1, 1, 'GSconfig_Serial_Number'],
                                [ 76, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'GSconfig_Model_Number'],
                                [ 85, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Module_Control'],
                                [ 86, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'GSconfig_Model_Select'],
                                [ 87, 1, 'float', 'SECS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_Low_Battery_Cut_Out_Delay'],
                                [ 88, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_High_Battery_Cut_Out_Voltage'],
                                [ 89, 1, 'float', 'VOLTS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_High_Battery_Cut_In_Voltage'],
                                [ 90, 1, 'float', 'SECS_U', 'GSconfig_DC_Voltage_SF', 1, 1, 'GSconfig_High_Battery_Cut_Out_Delay']
                            ],
                            64117: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'GS_Single_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_AC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_AC_Voltage_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_Frequency_SF'],
                                [ 8, 1, 'int16', 'NI_U', 'GS_Single_AC_Current_SF',0, 1, 'GS_Single_Inverter_Output_Current'],
                                [ 9, 1, 'int16', 'NI_U', 'GS_Single_AC_Current_SF',0, 1, 'GS_Single_Inverter_Charge_Current'],
                                [ 10, 1, 'int16', 'NI_U', 'GS_Single_AC_Current_SF',0, 1, 'GS_Single_Inverter_Buy_Current'],
                                [ 11, 1, 'int16', 'NI_U', 'GS_Single_AC_Current_SF',0, 1, 'GS_Single_Inverter_Sell_Current'],
                                [ 12, 1, 'float', 'VOLTS_U', 'GS_Single_AC_Voltage_SF',0, 1, 'GS_Single_Grid_Input_AC_Voltage'],
                                [ 13, 1, 'float', 'VOLTS_U', 'GS_Single_AC_Voltage_SF',0, 1, 'GS_Single_Gen_Input_AC_Voltage'],
                                [ 14, 1, 'float', 'VOLTS_U', 'GS_Single_AC_Voltage_SF',0, 1, 'GS_Single_AC_Output_Voltage'],
                                [ 15, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Single_Inverter_Operating_Mode'],
                                [ 16, 1, 'int16', 'BITFIELD_U', 'NI_SF', 0, 1, 'GS_Single_Error_Flags'],
                                [ 17, 1, 'int16', 'BITFIELD_U', 'NI_SF', 0, 1, 'GS_Single_Warning_Flags'],
                                [ 18, 1, 'float', 'VOLTS_U', 'GS_Single_DC_Voltage_SF',0, 1, 'GS_Single_Battery_Voltage'],
                                [ 19, 1, 'float', 'VOLTS_U', 'GS_Single_DC_Voltage_SF',0, 1, 'GS_Single_Temp_Comp_Target_Voltage'],
                                [ 20, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Single_AUX_Output_State'],
                                [ 21, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Single_AUX_Relay_Output_State'],
                                [ 22, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_L_Module_Transformer_Temp'],
                                [ 23, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_L_Module_Capacitor_Temp'],
                                [ 24, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_L_Module_FET_Temp'],
                                [ 25, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_R_Module_Transformer_Temp'],
                                [ 26, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_R_Module_Capacitor_Temp'],
                                [ 27, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_R_Module_FET_Temp'],
                                [ 28, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'GS_Single_Battery_Temperature'],
                                [ 29, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Single_AC_Input_Selection'],
                                [ 30, 1, 'int16', 'CYCLES_U', 'GS_Single_Frequency_SF', 0, 1, 'GS_Single_AC_Input_Frequency'],
                                [ 31, 1, 'float', 'VOLTS_U', 'GS_Single_AC_Voltage_SF',0, 1, 'GS_Single_AC_Input_Voltage'],
                                [ 32, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'GS_Single_AC_Input_State'],
                                [ 33, 1, 'float', 'VOLTS_U', 'GS_Single_AC_Voltage_SF',1, 1, 'GS_Single_Minimum_AC_Input_Voltage'],
                                [ 34, 1, 'float', 'VOLTS_U', 'GS_Single_AC_Voltage_SF',1, 1, 'GS_Single_Maximum_AC_Input_Voltage'],
                                [ 35, 1, 'int16', 'BITFIELD_U', 'NI_SF', 0, 1, 'GS_Single_Sell_Status'],
                                [ 36, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'GS_Single_kWh_SF'],
                                [ 37, 1, 'float', 'KWH_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_AC1_Buy_kWh'],
                                [ 38, 1, 'float', 'KWH_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_AC2_Buy_kWh'],
                                [ 39, 1, 'float', 'KWH_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_AC1_Sell_kWh'],
                                [ 40, 1, 'float', 'KWH_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_AC2_Sell_kWh'],
                                [ 41, 1, 'float', 'KWH_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Output_kWh'],
                                [ 42, 1, 'float', 'KWH_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Charger_kWh'],
                                [ 43, 1, 'float', 'KW_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Output_kW'],
                                [ 44, 1, 'float', 'KW_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Buy_kW'],
                                [ 45, 1, 'float', 'KW_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Sell_kW'],
                                [ 46, 1, 'float', 'KW_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Charge_kW'],
                                [ 47, 1, 'float', 'KW_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_Load_kW'],
                                [ 48, 1, 'float', 'KW_U', 'GS_Single_kWh_SF', 0, 1, 'GS_Single_AC_Couple_kW']
                            ],
                            64118: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FN_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'FN_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FN_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FN_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FN_DC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FN_Time_SF'],
                                [ 7, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FN_kWh_SF'],
                                [ 8, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FN_kW_SF'],
                                [ 9, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_A_Current'],
                                [ 10, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_B_Current'],
                                [ 11, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_C_Current'],
                                [ 12, 1, 'float', 'VOLTS_U', 'FN_DC_Voltage_SF', 0, 1, 'FN_Battery_Voltage'],
                                [ 13, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Battery_Current'],
                                [ 14, 1, 'int16', 'DEGREES_C_U', 'NI_SF', 0, 1, 'FN_Battery_Temperature'],
                                [ 15, 1, 'int16', 'BITFIELD_U', 'NI_SF', 0, 1, 'FN_Status_Flags'],
                                [ 16, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_A_Accumulated_AH'],
                                [ 17, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_A_Accumulated_kWh'],
                                [ 18, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_B_Accumulated_AH'],
                                [ 19, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_B_Accumulated_kWh'],
                                [ 20, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_C_Accumulated_AH'],
                                [ 21, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_C_Accumulated_kWh'],
                                [ 22, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Input_Current'],
                                [ 23, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Output_Current'],
                                [ 24, 1, 'float', 'KW_U', 'FN_kW_SF', 0, 1, 'FN_Input_kW'],
                                [ 25, 1, 'float', 'KW_U', 'FN_kW_SF', 0, 1, 'FN_Output_kW'],
                                [ 26, 1, 'float', 'KW_U', 'FN_kW_SF', 0, 1, 'FN_Net_kW'],
                                [ 27, 1, 'int16', 'DAYS_U', 'FN_Time_SF', 0, 1, 'FN_Days_Since_Charge_Parameters_Met'],
                                [ 28, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 0, 1, 'FN_State_Of_Charge'],
                                [ 29, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 0, 1, 'FN_Todays_Minimum_SOC'],
                                [ 30, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 0, 1, 'FN_Todays_Maximum_SOC'],
                                [ 31, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Todays_NET_Input_AH'],
                                [ 32, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Todays_NET_Input_kWh'],
                                [ 33, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Todays_NET_Output_AH'],
                                [ 34, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Todays_NET_Output_kWh'],
                                [ 35, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Todays_NET_Battery_AH'],
                                [ 36, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Todays_NET_Battery_kWh'],
                                [ 37, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Charge_Factor_Corrected_NET_Battery_AH'],
                                [ 38, 1, 'int16', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Charge_Factor_Corrected_NET_Battery_kWh'],
                                [ 39, 1, 'float', 'VOLTS_U', 'FN_DC_Voltage_SF', 1, 1, 'FN_Todays_Minimum_Battery_Voltage'],
                                [ 40, 2, 'int32', 'TIME_U', 'NI_SF', 0, 1, 'FN_Todays_Minimum_Battery_Time'],
                                [ 42, 1, 'float', 'VOLTS_U', 'FN_DC_Voltage_SF', 1, 1, 'FN_Todays_Maximum_Battery_Voltage'],
                                [ 43, 2, 'int32', 'TIME_U', 'NI_SF', 0, 1, 'FN_Todays_Maximum_Battery_Time'],
                                [ 45, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 0, 1, 'FN_Cycle_Charge_Factor'],
                                [ 46, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 0, 1, 'FN_Cycle_kWh_Charge_Efficiency'],
                                [ 47, 1, 'int16', 'DAYS_U', 'FN_Time_SF', 0, 1, 'FN_Total_Days_At_100_Percent'],
                                [ 48, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Lifetime_kAH_Removed'],
                                [ 49, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_A_Historical_Returned_To_Battery_AH'],
                                [ 50, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_A_Historical_Returned_To_Battery_kWh'],
                                [ 51, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_A_Historical_Removed_From_Battery_AH'],
                                [ 52, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_A_Historical_Removed_From_Battery_kWh'],
                                [ 53, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_A_Maximum_Charge_Rate'],
                                [ 54, 1, 'float', 'KW_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_A_Maximum_Charge_Rate_kW'],
                                [ 55, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_A_Maximum_Discharge_Rate'],
                                [ 56, 1, 'float', 'KW_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_A_Maximum_Discharge_Rate_kW'],
                                [ 57, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_B_Historical_Returned_To_Battery_AH'],
                                [ 58, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_B_Historical_Returned_To_Battery_kWh'],
                                [ 59, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_B_Historical_Removed_From_Battery_AH'],
                                [ 60, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_B_Historical_Removed_From_Battery_kWh'],
                                [ 61, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_B_Maximum_Charge_Rate'],
                                [ 62, 1, 'float', 'KW_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_B_Maximum_Charge_Rate_kW'],
                                [ 63, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_B_Maximum_Discharge_Rate'],
                                [ 64, 1, 'float', 'KW_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_B_Maximum_Discharge_Rate_kW'],
                                [ 65, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_C_Historical_Returned_To_Battery_AH'],
                                [ 66, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_C_Historical_Returned_To_Battery_kWh'],
                                [ 67, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FN_Shunt_C_Historical_Removed_From_Battery_AH'],
                                [ 68, 1, 'float', 'KWH_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_C_Historical_Removed_From_Battery_kWh'],
                                [ 69, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_C_Maximum_Charge_Rate'],
                                [ 70, 1, 'float', 'KW_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_C_Maximum_Charge_Rate_kW'],
                                [ 71, 1, 'int16', 'AMPS_U', 'FN_DC_Current_SF', 0, 1, 'FN_Shunt_C_Maximum_Discharge_Rate'],
                                [ 72, 1, 'float', 'KW_U', 'FN_kWh_SF', 0, 1, 'FN_Shunt_C_Maximum_Discharge_Rate_kW'],
                                [ 73, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FN_Shunt_A_Reset_Maximum_Data'],
                                [ 74, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FN_Shunt_A_Reset_Maximum_Data_Write_Complement'],
                                [ 75, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FN_Shunt_B_Reset_Maximum_Data'],
                                [ 76, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FN_Shunt_B_Reset_Maximum_Data_Write_Complement'],
                                [ 77, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FN_Shunt_C_Reset_Maximum_Data'],
                                [ 78, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FN_Shunt_C_Reset_Maximum_Data_Write_Complement']
                            ],
                            64119: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'FNconfig_SunSpec_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Port_Number'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_DC_Voltage_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_DC_Current_SF'],
                                [ 6, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_kWh_SF'],
                                [ 7, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Major_Firmware_Number'],
                                [ 8, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Mid_Firmware_Number'],
                                [ 9, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Minor_Firmware_Number'],
                                [ 10, 1, 'int16', 'AH_U', 'NI_SF', 1, 1, 'FNconfig_Battery_Capacity'],
                                [ 11, 1, 'float', 'VOLTS_U', 'FNconfig_DC_Voltage_SF', 1, 1, 'FNconfig_Charged_Volts'],
                                [ 12, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FNconfig_Charged_Time'],
                                [ 13, 1, 'int16', 'AMPS_U', 'FNconfig_DC_Current_SF', 1, 1, 'FNconfig_Battery_Charged_Amps'],
                                [ 14, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'FNconfig_Charge_Factor'],
                                [ 15, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FNconfig_Shunt_A_Enabled'],
                                [ 16, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FNconfig_Shunt_B_Enabled'],
                                [ 17, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FNconfig_Shunt_C_Enabled'],
                                [ 18, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FNconfig_Relay_Control'],
                                [ 19, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'FNconfig_Relay_Invert_Logic'],
                                [ 20, 1, 'float', 'VOLTS_U', 'FNconfig_DC_Voltage_SF', 1, 1, 'FNconfig_Relay_High_Voltage'],
                                [ 21, 1, 'float', 'VOLTS_U', 'FNconfig_DC_Voltage_SF', 1, 1, 'FNconfig_Relay_Low_Voltage'],
                                [ 22, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'FNconfig_Relay_SOC_High'],
                                [ 23, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 1, 1, 'FNconfig_Relay_SOC_Low'],
                                [ 24, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FNconfig_Relay_High_Enable_Delay'],
                                [ 25, 1, 'int16', 'MINS_U', 'NI_SF', 1, 1, 'FNconfig_Relay_Low_Enable_Delay'],
                                [ 26, 1, 'uhex4', 'DAYS_U', 'NI_SF', 1, 1, 'FNconfig_Set_Data_Log_Day_Offset'],
                                [ 27, 1, 'uhex4', 'DAYS_U', 'NI_SF', 0, 1, 'FNconfig_Get_Current_Data_Log_Day_Offset'],
                                [ 28, 1, 'int16', 'PERCENTAGE_U', 'NI_SF', 0, 1, 'FNconfig_Datalog_Minimum_SOC'],
                                [ 29, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FNconfig_Datalog_Input_AH'],
                                [ 30, 1, 'float', 'KWH_U', 'FNconfig_kWh_SF', 0, 1, 'FNconfig_Datalog_Input_kWh'],
                                [ 31, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FNconfig_Datalog_Output_AH'],
                                [ 32, 1, 'float', 'KWH_U', 'FNconfig_kWh_SF', 0, 1, 'FNconfig_Datalog_Output_kWh'],
                                [ 33, 1, 'int16', 'AH_U', 'NI_SF', 0, 1, 'FNconfig_Datalog_NET_AH'],
                                [ 34, 1, 'float', 'KWH_U', 'FNconfig_kWh_SF', 0, 1, 'FNconfig_Datalog_NET_kWh'],
                                [ 35, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Clear_Data_Log_Read'],
                                [ 36, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'FNconfig_Clear_Data_Log_Write_Complement'],
                                [ 37, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Serial_Number'],
                                [ 46, 9, 'string', 'NI_U', 'NI_SF', 0, 1, 'FNconfig_Model_Number']
                            ],
                            64120: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OB_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'OB_SunSpec_Length'],
                                [ 3, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'OB_DC_Voltage_SF'],
                                [ 4, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'OB_AC_Current_SF'],
                                [ 5, 1, 'uhex4', 'NI_U', 'NI_SF', 0, 1, 'OB_Time_SF'],
                                [ 6, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OB_Bulk_Charge_Enable_Disable'],
                                [ 7, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OB_Inverter_AC_Drop_Use'],
                                [ 8, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OB_Set_Inverter_Mode'],
                                [ 9, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OB_Grid_Tie_Mode'],
                                [ 10, 1, 'int16', 'NI_U', 'NI_SF', 1, 1, 'OB_Set_Inverter_Charger_Mode'],
                                [ 11, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OB_Control_Status'],
                                [ 12, 1, 'float', 'VOLTS_U', 'OB_DC_Voltage_SF', 1, 1, 'OB_Set_Sell_Voltage'],
                                [ 13, 1, 'int16', 'AMPS_U', 'OB_AC_Current_SF', 1, 1, 'OB_Set_Radian_Inverter_Sell_Current_Limit'],
                                [ 14, 1, 'float', 'VOLTS_U', 'OB_DC_Voltage_SF', 1, 1, 'OB_Set_Absorb_Voltage'],
                                [ 15, 1, 'float', 'HOURS_U', 'OB_Time_SF', 1, 1, 'OB_Set_Absorb_Time'],
                                [ 16, 1, 'float', 'VOLTS_U', 'OB_DC_Voltage_SF', 1, 1, 'OB_Set_Float_Voltage'],
                                [ 17, 1, 'float', 'HOURS_U', 'OB_Time_SF', 1, 1, 'OB_Set_Float_Time'],
                                [ 18, 1, 'float', 'AMPS_U', 'OB_AC_Current_SF', 1, 1, 'OB_Set_Inverter_Charger_Current_Limit'],
                                [ 19, 1, 'float', 'AMPS_U', 'OB_AC_Current_SF', 1, 1, 'OB_Set_Inverter_AC1_Current_Limit'],
                                [ 20, 1, 'float', 'AMPS_U', 'OB_AC_Current_SF', 1, 1, 'OB_Set_Inverter_AC2_Current_Limit'],
                                [ 21, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 1, 1, 'OB_Set_AGS_OP_Mode'],
                                [ 22, 1, 'int16', 'ENUMERATED_U', 'NI_SF', 0, 1, 'OB_AGS_Operational_State'],
                                [ 23, 1, 'int16', 'SECS_U', 'NI_SF', 0, 1, 'OB_AGS_Operational_State_Timer'],
                                [ 24, 2, 'int32', 'TIME_U', 'NI_SF', 0, 1, 'OB_Gen_Last_Run_Start_Time_GMT'],
                                [ 26, 2, 'int32', 'SECS_U', 'NI_SF', 0, 1, 'OB_Gen_Last_Run_Duration'],
                                [ 28, 1, 'uhex4', 'NI_U', 'NI_SF', 1, 1, 'OB_Set_AC_Output_Freq_Offline_Mode'],
                                [ 29, 1, 'uhex4', 'NI_U', 'OB_DC_Voltage_SF', 1, 1, 'OB_Set_AC_Output_Offline_Freq']
                            ],
                            64255: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'OP_stats_Length'],
                                [ 3, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_min'],
                                [ 4, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_max'],
                                [ 5, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_ave'],
                                [ 6, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_attempts'],
                                [ 7, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_errors'],
                                [ 8, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_timeouts'],
                                [ 9, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Bt_packet_timeout'],
                                [ 10, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_min'],
                                [ 11, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_max'],
                                [ 12, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_ave'],
                                [ 13, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_attempts'],
                                [ 14, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_errors'],
                                [ 15, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_timeouts'],
                                [ 16, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mp_packet_timeout'],
                                [ 17, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_min'],
                                [ 18, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_max'],
                                [ 19, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_ave'],
                                [ 20, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_attempts'],
                                [ 21, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_errors'],
                                [ 22, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_timeouts'],
                                [ 23, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Cu_packet_timeout'],
                                [ 24, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_min'],
                                [ 25, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_max'],
                                [ 26, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_ave'],
                                [ 27, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_attempts'],
                                [ 28, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_errors'],
                                [ 29, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_timeouts'],
                                [ 30, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Su_packet_timeout'],
                                [ 31, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_min'],
                                [ 32, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_max'],
                                [ 33, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_ave'],
                                [ 34, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_attempts'],
                                [ 35, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_errors'],
                                [ 36, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_timeouts'],
                                [ 37, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Pg_packet_timeout'],
                                [ 38, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_min'],
                                [ 39, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_max'],
                                [ 40, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_ave'],
                                [ 41, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_attempts'],
                                [ 42, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_errors'],
                                [ 43, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_timeouts'],
                                [ 44, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Mb_packet_timeout'],
                                [ 45, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_min'],
                                [ 46, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_max'],
                                [ 47, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_ave'],
                                [ 48, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_attempts'],
                                [ 49, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_errors'],
                                [ 50, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_timeouts'],
                                [ 51, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Fu_packet_timeout'],
                                [ 52, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_min'],
                                [ 53, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_max'],
                                [ 54, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_ave'],
                                [ 55, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_attempts'],
                                [ 56, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_errors'],
                                [ 57, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_timeouts'],
                                [ 58, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'OP_stats_Ev_packet_timeout']
                            ],
                            65535: [
                                [ 1, 1, 'int16', 'NI_U', 'NI_SF', 0, 1, 'END_SunSpec_DID'],
                                [ 2, 1, 'int16', 'REGISTERS_U', 'NI_SF', 0, 1, 'END_SunSpec_Length']
                            ]
                        }

